# Generated by Django 3.0.8 on 2020-08-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20200820_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
