# Generated by Django 3.0.8 on 2020-07-23 17:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
