# Generated by Django 3.0.8 on 2020-08-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200813_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='pages.PageCategory'),
        ),
    ]
