# Generated by Django 3.0.8 on 2020-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200807_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-update_at',)},
        ),
        migrations.AddField(
            model_name='appointment',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', max_length=10),
        ),
    ]
