# Generated by Django 3.0.8 on 2020-08-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200825_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-created_at', 'status')},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='appointment.Appointment'),
        ),
    ]
