# Generated by Django 3.0.8 on 2020-08-27 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20200825_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='appointment.Appointment'),
        ),
    ]
