# Generated by Django 3.0.8 on 2020-07-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slugfield',
            new_name='slug',
        ),
    ]
