# Generated by Django 3.0.8 on 2020-07-25 00:16

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('doc_image', models.ImageField(upload_to='')),
                ('specialization', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=70, null=True)),
                ('biography', ckeditor_uploader.fields.RichTextUploadingField()),
                ('eduction', ckeditor.fields.RichTextField()),
                ('contact_info', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
