# Generated by Django 3.0.8 on 2020-07-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_eduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_image',
            field=models.ImageField(upload_to='doctors/'),
        ),
    ]
